version: 2
checks:
  method-lines:
    config:
      threshold: 100
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 15
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
- "src/data/"
- "src/test/"
- "Dockerfile"
- "Gruntfile.js"
- "**/vendor/"
