version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.12
        environment:
          SERVER_WORKERS: 2
          MI_PROTOCOL: "http"
          MI_SECRET: "JKL123"
          COOKIE_SECRET: "abc123"
          JWT_SECRET: "abcd1234"
          URL_USING_MI: "http://using-mi.com"
          URL_KIM_PRINCIPLES: "http://kim-principles.com"
      - image: postgres:9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: export-wins-data
      - image: ukti/export-wins-data
        environment:
          DEBUG: "True"
          API_DEBUG: "True"
          SECRET_KEY: "ABC123"
          ADMIN_SECRET: "DEF456"
          UI_SECRET: "GHI789"
          MI_SECRET: "JKL123"
          DATA_SECRET: "QWERTY123"
          DATABASE_URL: "postgres://postgres@localhost/export-wins-data"
          EMAIL_HOST: "$EMAIL_HOST"
          EMAIL_PORT: "$EMAIL_PORT"
          VCAP_SERVICES: '{"redis": [{"credentials": {"uri": "redis://localhost:7000/"}}]}'
          ACTIVITY_STREAM_ACCESS_KEY_ID: "123"
          ACTIVITY_STREAM_SECRET_ACCESS_KEY: "456"
        command: ./start-wait-for-db.sh
      - image: grokzen/redis-cluster:3.2.11
        environment:
          CLUSTER_ONLY: true
      - image: selenium/standalone-chrome:3.7
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      #- run: npm run check:backend
      - run: npm rebuild node-sass
      - run: npm test && npm run coverage
      - run: npm run build:dist
      - save_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "dist/node_modules"
      - run:
          command: npm start
          background: true
      - run: TEST_BROWSER=chrome npm run test:integration
      - store_artifacts:
          path: src/test/ci/output/screenshots
          destination: screenshots
      - store_artifacts:
          path: src/test/ci/output/accessibility-reports
          destination: accessibility-reports
      - store_artifacts:
          path: coverage
          destination: coverage
